-- 达梦：扫描字段信息
-- 注意：ALL_COL_COMMENTS.OWNER 是建表用户名（如 SYSDBA），而 ALL_TAB_COLUMNS.OWNER 是 schema 名（如 ZOE_BASIC_SYS）
-- 达梦 ALL_COL_COMMENTS 额外提供 SCHEMA_NAME 列，需用 cc.SCHEMA_NAME 关联 tc.OWNER
SELECT
    tc.TABLE_NAME,
    tc.COLUMN_NAME,
    tc.DATA_TYPE || CASE
        WHEN tc.DATA_LENGTH IS NOT NULL AND tc.DATA_TYPE IN ('VARCHAR', 'VARCHAR2', 'CHAR')
        THEN '(' || tc.DATA_LENGTH || ')'
        WHEN tc.DATA_PRECISION IS NOT NULL AND tc.DATA_SCALE IS NOT NULL
        THEN '(' || tc.DATA_PRECISION || ',' || tc.DATA_SCALE || ')'
        WHEN tc.DATA_PRECISION IS NOT NULL
        THEN '(' || tc.DATA_PRECISION || ')'
        ELSE ''
    END AS COLUMN_TYPE,
    tc.NULLABLE AS IS_NULLABLE,
    tc.DATA_DEFAULT AS COLUMN_DEFAULT,
    CASE WHEN pk.COLUMN_NAME IS NOT NULL THEN 'PRI' ELSE '' END AS COLUMN_KEY,
    cc.COMMENTS AS COLUMN_COMMENT,
    tc.COLUMN_ID AS ORDINAL_POSITION
FROM ALL_TAB_COLUMNS tc
LEFT JOIN ALL_COL_COMMENTS cc
    ON tc.TABLE_NAME = cc.TABLE_NAME
    AND tc.COLUMN_NAME = cc.COLUMN_NAME
    AND tc.OWNER = cc.SCHEMA_NAME
LEFT JOIN (
    SELECT cols.TABLE_NAME, cols.COLUMN_NAME, cols.OWNER
    FROM ALL_CONSTRAINTS cons
    JOIN ALL_CONS_COLUMNS cols
        ON cons.CONSTRAINT_NAME = cols.CONSTRAINT_NAME
        AND cons.OWNER = cols.OWNER
    WHERE cons.CONSTRAINT_TYPE = 'P'
) pk ON tc.TABLE_NAME = pk.TABLE_NAME
    AND tc.COLUMN_NAME = pk.COLUMN_NAME
    AND tc.OWNER = pk.OWNER
WHERE tc.OWNER = :1
ORDER BY tc.TABLE_NAME, tc.COLUMN_ID;
