-- 达梦：扫描外键关系
SELECT
    cc.TABLE_NAME,
    cc.COLUMN_NAME,
    (
        SELECT pc.TABLE_NAME
        FROM ALL_CONSTRAINTS pc
        WHERE pc.CONSTRAINT_NAME = rc.R_CONSTRAINT_NAME
          AND pc.OWNER = rc.OWNER
    ) AS REFERENCED_TABLE_NAME,
    (
        SELECT pc_col.COLUMN_NAME
        FROM ALL_CONS_COLUMNS pc_col
        WHERE pc_col.CONSTRAINT_NAME = rc.R_CONSTRAINT_NAME
          AND pc_col.OWNER = rc.OWNER
          AND pc_col.POSITION = cc.POSITION
    ) AS REFERENCED_COLUMN_NAME,
    rc.CONSTRAINT_NAME
FROM ALL_CONSTRAINTS rc
JOIN ALL_CONS_COLUMNS cc
    ON rc.CONSTRAINT_NAME = cc.CONSTRAINT_NAME
    AND rc.OWNER = cc.OWNER
WHERE rc.CONSTRAINT_TYPE = 'R'
  AND rc.OWNER = :1
ORDER BY cc.TABLE_NAME, rc.CONSTRAINT_NAME;
