-- 达梦：扫描索引信息
SELECT
    i.TABLE_NAME,
    i.INDEX_NAME,
    ic.COLUMN_NAME,
    CASE WHEN i.UNIQUENESS = 'UNIQUE' THEN 0 ELSE 1 END AS NON_UNIQUE,
    ic.COLUMN_POSITION AS SEQ_IN_INDEX
FROM ALL_INDEXES i
JOIN ALL_IND_COLUMNS ic
    ON i.INDEX_NAME = ic.INDEX_NAME
    AND i.OWNER = ic.INDEX_OWNER
WHERE i.OWNER = :1
ORDER BY i.TABLE_NAME, i.INDEX_NAME, ic.COLUMN_POSITION;
