-- Oracle：扫描表清单
SELECT
    t.TABLE_NAME,
    c.COMMENTS AS TABLE_COMMENT,
    t.NUM_ROWS AS TABLE_ROWS
FROM ALL_TABLES t
LEFT JOIN ALL_TAB_COMMENTS c
    ON t.TABLE_NAME = c.TABLE_NAME
    AND t.OWNER = c.OWNER
WHERE t.OWNER = :1
ORDER BY t.TABLE_NAME;
